# Generated by Django 2.1.7 on 2019-05-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11, verbose_name='Phone')),
                ('creditLine', models.CharField(max_length=10, verbose_name='credit line')),
                ('hasCreditLine', models.BooleanField(default=False)),
                ('balance', models.DecimalField(default=0, max_length=4)),
                ('isMember', models.BooleanField(default=False)),
                ('joinDate', models.DateTimeField()),
                ('subjectInterests', models.CharField(max_length=255)),
                ('modelTypeInterests', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectArea', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='customers.Customer')),
            ],
        ),
    ]
