export { default as customers } from './customers/reducers'
export { default as sales } from './sales/reducers'
export { default as models } from './models/reducers'
export { default as locations } from './locations/reducers'
export { default as suppliers } from './suppliers/reducers'
export { default as users } from './users/reducers'