# Generated by Django 2.1.7 on 2019-05-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productModel', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('discount', models.FloatField()),
                ('items', models.CharField(max_length=255)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id', to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelSupp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelSupp', to='productModel.ModelSupp')),
                ('saleRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleRecord', to='sale.SaleRecord')),
            ],
        ),
    ]
