# Generated by Django 2.1.7 on 2019-05-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSupp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('availability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('value', models.DecimalField()),
                ('items', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Not relevant'), (2, 'Review'), (3, 'Maybe relevant'), (4, 'Relevant'), (5, 'Leading candidate')], default=1)),
                ('subject', models.IntegerField(choices=[(1, 'Not relevant'), (2, 'Review'), (3, 'Maybe relevant'), (4, 'Relevant'), (5, 'Leading candidate')], default=1)),
                ('inStock', models.IntegerField()),
                ('price', models.DecimalField()),
                ('dateAcquired', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('availabilty', models.BooleanField(default=False)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('creditLine', models.CharField(max_length=10)),
                ('hasCreditLine', models.BooleanField(default=False)),
                ('balance', models.DecimalField(max_length=4)),
                ('deliveNotesr', models.CharField(max_length=255)),
                ('contactPerson', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCatalogue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField()),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id', to='productModel.PModel')),
                ('supplierId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id', to='productModel.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='supplierId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id', to='productModel.Supplier'),
        ),
        migrations.AddField(
            model_name='modelsupp',
            name='pModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pModel', to='productModel.PModel'),
        ),
        migrations.AddField(
            model_name='modelsupp',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='productModel.Supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='modelsupp',
            unique_together={('supplier', 'pModel')},
        ),
    ]
