# Generated by Django 2.2 on 2019-04-22 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('subjectArea', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('deliverDetail', models.CharField(max_length=255)),
                ('contactPerson', models.CharField(max_length=255)),
                ('creditLine', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelSupplyBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('availability', models.IntegerField()),
                ('sModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productModel.PModel')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productModel.Supplier')),
            ],
        ),
    ]
